\set ON_ERROR_STOP on

-- ============================================================================
-- CAB System MVP - PostgreSQL initialization
-- One PostgreSQL container, seven logical databases.
-- Cross-service IDs are logical references only; no physical FK across DBs.
-- ============================================================================

CREATE DATABASE auth_db;
CREATE DATABASE customer_db;
CREATE DATABASE driver_db;
CREATE DATABASE booking_db;
CREATE DATABASE trip_db;
CREATE DATABASE payment_db;
CREATE DATABASE review_db;

-- auth_db --------------------------------------------------------------------
\connect auth_db
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE user_account (
  uid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      VARCHAR(100) NOT NULL UNIQUE,
  pw_hash    VARCHAR(255) NOT NULL,
  role       VARCHAR(20) NOT NULL CHECK (role IN ('CUSTOMER','DRIVER','ADMIN')),
  s          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (s IN ('ACTIVE','INACTIVE')),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- customer_db ----------------------------------------------------------------
\connect customer_db
CREATE TABLE customer_profile (
  cid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid        BIGINT NOT NULL UNIQUE,
  name       VARCHAR(100) NOT NULL,
  addr       VARCHAR(255),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- driver_db ------------------------------------------------------------------
\connect driver_db
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE driver (
  did        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid        BIGINT NOT NULL UNIQUE,
  ap         VARCHAR(30) NOT NULL DEFAULT 'PENDING_APPROVAL'
             CHECK (ap IN ('PENDING_APPROVAL','APPROVED','REJECTED')),
  av         VARCHAR(20) NOT NULL DEFAULT 'OFFLINE'
             CHECK (av IN ('OFFLINE','AVAILABLE','BUSY')),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver_profile (
  did        BIGINT PRIMARY KEY REFERENCES driver(did) ON DELETE CASCADE,
  name       VARCHAR(100) NOT NULL,
  lic_enc    VARCHAR(255),
  key_ver    INTEGER NOT NULL DEFAULT 1,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver_location (
  did        BIGINT PRIMARY KEY REFERENCES driver(did) ON DELETE CASCADE,
  lat        DECIMAL(10,6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng        DECIMAL(10,6) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  rec_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_driver_location_geog
ON driver_location
USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography));

CREATE TABLE vehicle (
  vid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  did        BIGINT NOT NULL REFERENCES driver(did) ON DELETE CASCADE,
  vt         VARCHAR(50) NOT NULL,
  plate      VARCHAR(20) NOT NULL UNIQUE,
  brand      VARCHAR(50),
  model      VARCHAR(50),
  s          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (s IN ('ACTIVE','INACTIVE')),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver_application (
  appid      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  did        BIGINT NOT NULL REFERENCES driver(did) ON DELETE CASCADE,
  vid        BIGINT NOT NULL REFERENCES vehicle(vid) ON DELETE CASCADE,
  s          VARCHAR(30) NOT NULL DEFAULT 'PENDING_APPROVAL'
             CHECK (s IN ('PENDING_APPROVAL','APPROVED','REJECTED')),
  rev_uid    BIGINT,
  sub_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rev_at     TIMESTAMPTZ
);

-- booking_db -----------------------------------------------------------------
\connect booking_db
CREATE TABLE booking (
  bid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid        BIGINT NOT NULL,
  p_lat      DECIMAL(10,6) NOT NULL CHECK (p_lat BETWEEN -90 AND 90),
  p_lng      DECIMAL(10,6) NOT NULL CHECK (p_lng BETWEEN -180 AND 180),
  p_addr     VARCHAR(255),
  d_lat      DECIMAL(10,6) NOT NULL CHECK (d_lat BETWEEN -90 AND 90),
  d_lng      DECIMAL(10,6) NOT NULL CHECK (d_lng BETWEEN -180 AND 180),
  d_addr     VARCHAR(255),
  vt         VARCHAR(50) NOT NULL,
  s          VARCHAR(30) NOT NULL DEFAULT 'SEARCHING'
             CHECK (s IN ('SEARCHING','ASSIGNED','NO_DRIVER_FOUND')),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ass_at     TIMESTAMPTZ
);

CREATE INDEX idx_booking_customer ON booking(cid, c_at DESC);

CREATE TABLE driver_offer (
  oid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid        BIGINT NOT NULL UNIQUE REFERENCES booking(bid) ON DELETE CASCADE,
  did        BIGINT NOT NULL,
  vid        BIGINT,
  s          VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (s IN ('OPEN','ACCEPTED')),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acc_at     TIMESTAMPTZ
);

CREATE TABLE driver_assignment (
  aid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid        BIGINT NOT NULL UNIQUE REFERENCES booking(bid) ON DELETE CASCADE,
  oid        BIGINT NOT NULL UNIQUE REFERENCES driver_offer(oid) ON DELETE CASCADE,
  did        BIGINT NOT NULL,
  vid        BIGINT NOT NULL,
  ass_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- trip_db --------------------------------------------------------------------
\connect trip_db
CREATE TABLE trip (
  tid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid        BIGINT NOT NULL UNIQUE,
  cid        BIGINT NOT NULL,
  did        BIGINT NOT NULL,
  vid        BIGINT NOT NULL,
  s          VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED'
             CHECK (s IN ('ASSIGNED','ARRIVED','IN_PROGRESS','COMPLETED','CANCELED')),
  paid       BOOLEAN NOT NULL DEFAULT FALSE,
  r          VARCHAR(255),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  done_at    TIMESTAMPTZ,
  can_at     TIMESTAMPTZ
);

CREATE TABLE trip_status_history (
  hid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tid        BIGINT NOT NULL REFERENCES trip(tid) ON DELETE CASCADE,
  from_s     VARCHAR(20),
  to_s       VARCHAR(20) NOT NULL,
  chg_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trip_location (
  lid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tid        BIGINT NOT NULL REFERENCES trip(tid) ON DELETE CASCADE,
  lat        DECIMAL(10,6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng        DECIMAL(10,6) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  rec_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_trip_location_trip ON trip_location(tid, rec_at DESC);

-- payment_db -----------------------------------------------------------------
\connect payment_db
CREATE TABLE payment (
  pid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bid        BIGINT NOT NULL UNIQUE,
  tid        BIGINT UNIQUE,
  cid        BIGINT NOT NULL,
  amt        DECIMAL(12,2) NOT NULL DEFAULT 50000 CHECK (amt >= 0),
  eligible   BOOLEAN NOT NULL DEFAULT FALSE,
  s          VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (s IN ('PENDING','COMPLETED')),
  ikey       VARCHAR(100) UNIQUE,
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at    TIMESTAMPTZ
);

-- review_db ------------------------------------------------------------------
\connect review_db
CREATE TABLE review (
  rid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tid        BIGINT NOT NULL UNIQUE,
  cid        BIGINT NOT NULL,
  did        BIGINT NOT NULL,
  star       INTEGER NOT NULL CHECK (star BETWEEN 1 AND 5),
  cmt        VARCHAR(255),
  c_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
