\set ON_ERROR_STOP on

-- CAB System PostgreSQL bootstrap.
-- Local development uses one PostgreSQL instance with
-- 10 logically isolated databases.
--
-- IMPORTANT:
-- Cross-context IDs are logical references only.
-- No physical FK may cross microservice databases.

CREATE DATABASE auth_db;
CREATE DATABASE customer_db;
CREATE DATABASE driver_db;
CREATE DATABASE booking_db;
CREATE DATABASE trip_db;
CREATE DATABASE payment_db;
CREATE DATABASE notification_db;
CREATE DATABASE review_db;
CREATE DATABASE reporting_db;
CREATE DATABASE audit_db;


-- =========================================================
-- Identity & Access
-- auth-service -> auth_db
-- =========================================================

\connect auth_db


CREATE TABLE role (
    role_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name     VARCHAR(50) NOT NULL UNIQUE,
    description   VARCHAR(255)
);


CREATE TABLE permission (
    permission_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code  VARCHAR(80) NOT NULL UNIQUE,
    description      VARCHAR(255)
);


CREATE TABLE role_permission (
    role_id        INTEGER NOT NULL,
    permission_id  INTEGER NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES role(role_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES permission(permission_id)
        ON DELETE CASCADE
);


CREATE TABLE user_account (
    user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone          VARCHAR(20) NOT NULL UNIQUE,
    email          VARCHAR(100) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role_id        INTEGER NOT NULL,
    status         VARCHAR(20) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_account_role
        FOREIGN KEY (role_id)
        REFERENCES role(role_id),

    CONSTRAINT ck_user_account_status
        CHECK (
            status IN (
                'ACTIVE',
                'DISABLED'
            )
        )
);


CREATE TABLE refresh_token (
    token_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    token_hash    VARCHAR(255) NOT NULL UNIQUE,
    expires_at    TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ,
    device_info   VARCHAR(255),

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
        REFERENCES user_account(user_id)
        ON DELETE CASCADE
);


CREATE TABLE otp_verification (
    otp_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER,
    phone          VARCHAR(20) NOT NULL,
    otp_hash       VARCHAR(255) NOT NULL,
    purpose        VARCHAR(50) NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    verified_at    TIMESTAMPTZ,
    attempt_count  INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_otp_verification_user
        FOREIGN KEY (user_id)
        REFERENCES user_account(user_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_otp_attempt_count
        CHECK (attempt_count >= 0)
);


CREATE INDEX idx_user_account_role_status
    ON user_account(role_id, status);

CREATE INDEX idx_refresh_token_user
    ON refresh_token(user_id);

CREATE INDEX idx_otp_verification_phone_purpose
    ON otp_verification(phone, purpose);



-- =========================================================
-- Customer Management
-- customer-service -> customer_db
--
-- user_id is a logical reference to auth_db.user_account.
-- No physical cross-database FK.
-- =========================================================

\connect customer_db


CREATE TABLE customer_profile (
    customer_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER NOT NULL UNIQUE,
    full_name      VARCHAR(100) NOT NULL,
    address        VARCHAR(255),
    date_of_birth  DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_customer_profile_full_name
    ON customer_profile(full_name);



-- =========================================================
-- Driver & Vehicle Management
-- driver-service -> driver_db
--
-- user_id and reviewed_by_user_id are logical references
-- to auth_db.
-- =========================================================

\connect driver_db


CREATE EXTENSION IF NOT EXISTS postgis;


CREATE TABLE driver (
    driver_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL UNIQUE,
    approval_status      VARCHAR(20) NOT NULL,
    availability_status  VARCHAR(20) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_driver_approval_status
        CHECK (
            approval_status IN (
                'PENDING_APPROVAL',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_driver_availability_status
        CHECK (
            availability_status IN (
                'OFFLINE',
                'AVAILABLE',
                'BUSY'
            )
        )
);


CREATE TABLE driver_profile (
    driver_id                  INTEGER PRIMARY KEY,
    full_name                  VARCHAR(100) NOT NULL,
    address                    VARCHAR(255),
    date_of_birth              DATE,
    driver_license_ciphertext  VARCHAR(255) NOT NULL,
    encryption_key_version     INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_driver_profile_driver
        FOREIGN KEY (driver_id)
        REFERENCES driver(driver_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_driver_profile_key_version
        CHECK (encryption_key_version >= 1)
);


CREATE TABLE driver_location (
    driver_id    INTEGER PRIMARY KEY,
    latitude     DECIMAL(10,6) NOT NULL,
    longitude    DECIMAL(10,6) NOT NULL,
    recorded_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_driver_location_driver
        FOREIGN KEY (driver_id)
        REFERENCES driver(driver_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_driver_location_latitude
        CHECK (
            latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_driver_location_longitude
        CHECK (
            longitude BETWEEN -180 AND 180
        )
);


CREATE TABLE vehicle_type (
    vehicle_type_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(50) NOT NULL,
    description      VARCHAR(255),
    status           VARCHAR(20) NOT NULL,

    CONSTRAINT ck_vehicle_type_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


CREATE TABLE vehicle (
    vehicle_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id        INTEGER NOT NULL,
    vehicle_type_id  INTEGER NOT NULL,
    license_plate    VARCHAR(20) NOT NULL UNIQUE,
    brand            VARCHAR(50),
    model            VARCHAR(50),
    status           VARCHAR(20) NOT NULL,

    CONSTRAINT fk_vehicle_driver
        FOREIGN KEY (driver_id)
        REFERENCES driver(driver_id),

    CONSTRAINT fk_vehicle_vehicle_type
        FOREIGN KEY (vehicle_type_id)
        REFERENCES vehicle_type(vehicle_type_id),

    CONSTRAINT ck_vehicle_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


CREATE TABLE driver_application (
    application_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id            INTEGER NOT NULL,
    vehicle_id           INTEGER NOT NULL,
    status               VARCHAR(20) NOT NULL,
    reviewed_by_user_id  INTEGER,
    rejection_reason     VARCHAR(255),
    submitted_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at          TIMESTAMPTZ,

    CONSTRAINT fk_driver_application_driver
        FOREIGN KEY (driver_id)
        REFERENCES driver(driver_id),

    CONSTRAINT fk_driver_application_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES vehicle(vehicle_id),

    CONSTRAINT ck_driver_application_status
        CHECK (
            status IN (
                'PENDING_APPROVAL',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_driver_application_review
        CHECK (
            (
                status = 'PENDING_APPROVAL'
                AND reviewed_at IS NULL
            )
            OR
            (
                status IN (
                    'APPROVED',
                    'REJECTED'
                )
                AND reviewed_at IS NOT NULL
            )
        )
);


CREATE INDEX idx_driver_eligibility
    ON driver(
        approval_status,
        availability_status
    );


CREATE INDEX idx_vehicle_driver_status
    ON vehicle(
        driver_id,
        status
    );


CREATE INDEX idx_vehicle_type_status
    ON vehicle(
        vehicle_type_id,
        status
    );


CREATE INDEX idx_driver_application_status
    ON driver_application(
        status,
        submitted_at
    );


-- PostGIS functional spatial index.
-- No extra location column is introduced because it does
-- not exist in ERD FINAL.
CREATE INDEX idx_driver_location_geography
    ON driver_location
    USING GIST (
        (
            ST_SetSRID(
                ST_MakePoint(
                    longitude::DOUBLE PRECISION,
                    latitude::DOUBLE PRECISION
                ),
                4326
            )::geography
        )
    );



-- =========================================================
-- Booking Management
-- booking-service -> booking_db
--
-- customer_id, driver_id, vehicle_id and
-- requested_vehicle_type_id are cross-context logical refs.
-- =========================================================

\connect booking_db


CREATE TABLE booking (
    booking_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id                INTEGER NOT NULL,

    pickup_latitude            DECIMAL(10,6) NOT NULL,
    pickup_longitude           DECIMAL(10,6) NOT NULL,
    pickup_address             VARCHAR(255),

    destination_latitude       DECIMAL(10,6) NOT NULL,
    destination_longitude      DECIMAL(10,6) NOT NULL,
    destination_address        VARCHAR(255),

    requested_vehicle_type_id  INTEGER NOT NULL,

    status                     VARCHAR(20) NOT NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_booking_pickup_latitude
        CHECK (
            pickup_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_booking_pickup_longitude
        CHECK (
            pickup_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_booking_destination_latitude
        CHECK (
            destination_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_booking_destination_longitude
        CHECK (
            destination_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_booking_status
        CHECK (
            status IN (
                'CREATED',
                'SEARCHING',
                'ASSIGNED',
                'NO_DRIVER_FOUND'
            )
        )
);


CREATE TABLE driver_offer (
    offer_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     INTEGER NOT NULL,

    driver_id      INTEGER NOT NULL,
    vehicle_id     INTEGER NOT NULL,

    status         VARCHAR(20) NOT NULL,

    expires_at     TIMESTAMPTZ NOT NULL,
    responded_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_driver_offer_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_driver_offer_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REJECTED',
                'EXPIRED'
            )
        ),

    CONSTRAINT ck_driver_offer_response
        CHECK (
            (
                status = 'PENDING'
                AND responded_at IS NULL
            )
            OR
            (
                status IN (
                    'ACCEPTED',
                    'REJECTED',
                    'EXPIRED'
                )
            )
        )
);


CREATE TABLE driver_assignment (
    assignment_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id     INTEGER NOT NULL UNIQUE,
    offer_id       INTEGER NOT NULL UNIQUE,

    driver_id      INTEGER NOT NULL,
    vehicle_id     INTEGER NOT NULL,

    assigned_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_driver_assignment_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_driver_assignment_offer
        FOREIGN KEY (offer_id)
        REFERENCES driver_offer(offer_id)
);


CREATE INDEX idx_booking_customer_created
    ON booking(
        customer_id,
        created_at DESC
    );


CREATE INDEX idx_booking_status
    ON booking(status);


CREATE INDEX idx_driver_offer_booking_status
    ON driver_offer(
        booking_id,
        status
    );


CREATE INDEX idx_driver_offer_driver_status
    ON driver_offer(
        driver_id,
        status
    );



-- =========================================================
-- Trip Management
-- trip-service -> trip_db
--
-- booking/customer/driver/vehicle/vehicle_type/user IDs
-- are cross-context logical references.
-- =========================================================

\connect trip_db


CREATE TABLE trip (
    trip_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id            INTEGER NOT NULL UNIQUE,
    customer_id           INTEGER NOT NULL,
    driver_id             INTEGER NOT NULL,
    vehicle_id            INTEGER NOT NULL,
    vehicle_type_id       INTEGER NOT NULL,

    distance_km           DECIMAL(10,2),

    status                VARCHAR(20) NOT NULL,

    estimated_arrival_at  TIMESTAMPTZ,

    assigned_at           TIMESTAMPTZ,
    arrived_at            TIMESTAMPTZ,
    picked_up_at          TIMESTAMPTZ,
    started_at            TIMESTAMPTZ,

    completed_at          TIMESTAMPTZ,

    canceled_at           TIMESTAMPTZ,
    cancel_reason         VARCHAR(255),
    canceled_by_user_id   INTEGER,

    CONSTRAINT ck_trip_distance
        CHECK (
            distance_km IS NULL
            OR distance_km >= 0
        ),

    CONSTRAINT ck_trip_status
        CHECK (
            status IN (
                'ASSIGNED',
                'ARRIVED',
                'PICKED_UP',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELED'
            )
        ),

    CONSTRAINT ck_trip_terminal_data
        CHECK (
            (
                status = 'COMPLETED'
                AND completed_at IS NOT NULL
                AND distance_km IS NOT NULL
            )
            OR
            (
                status = 'CANCELED'
                AND canceled_at IS NOT NULL
                AND cancel_reason IS NOT NULL
            )
            OR
            (
                status NOT IN (
                    'COMPLETED',
                    'CANCELED'
                )
            )
        )
);


CREATE TABLE trip_status_history (
    history_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             INTEGER NOT NULL,

    from_status         VARCHAR(20),
    to_status           VARCHAR(20) NOT NULL,

    changed_by_user_id  INTEGER,
    reason              VARCHAR(255),

    changed_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_trip_status_history_trip
        FOREIGN KEY (trip_id)
        REFERENCES trip(trip_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_trip_history_from_status
        CHECK (
            from_status IS NULL
            OR from_status IN (
                'ASSIGNED',
                'ARRIVED',
                'PICKED_UP',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELED'
            )
        ),

    CONSTRAINT ck_trip_history_to_status
        CHECK (
            to_status IN (
                'ASSIGNED',
                'ARRIVED',
                'PICKED_UP',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELED'
            )
        )
);


CREATE INDEX idx_trip_customer
    ON trip(
        customer_id,
        assigned_at DESC
    );


CREATE INDEX idx_trip_driver_status
    ON trip(
        driver_id,
        status
    );


CREATE INDEX idx_trip_status
    ON trip(status);


CREATE INDEX idx_trip_history_trip_changed
    ON trip_status_history(
        trip_id,
        changed_at
    );



-- =========================================================
-- Fare & Payment
-- payment-service -> payment_db
--
-- trip/customer/vehicle_type IDs are logical references.
-- =========================================================

\connect payment_db


CREATE TABLE fare (
    fare_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    trip_id                  INTEGER NOT NULL UNIQUE,
    vehicle_type_id          INTEGER NOT NULL,

    amount                   DECIMAL(10,2) NOT NULL,
    currency                 VARCHAR(3) NOT NULL,

    pricing_data             JSON NOT NULL,
    pricing_policy_snapshot  JSON NOT NULL,

    calculated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_fare_amount
        CHECK (amount >= 0)
);


CREATE TABLE payment (
    payment_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fare_id             INTEGER NOT NULL UNIQUE,

    trip_id             INTEGER NOT NULL,
    customer_id         INTEGER NOT NULL,

    amount              DECIMAL(10,2) NOT NULL,
    currency            VARCHAR(3) NOT NULL,

    payment_method      VARCHAR(50) NOT NULL,
    payment_status      VARCHAR(20) NOT NULL,

    idempotency_key     VARCHAR(100) NOT NULL UNIQUE,

    provider_reference  VARCHAR(100),
    failure_reason      VARCHAR(255),

    paid_at             TIMESTAMPTZ,

    CONSTRAINT fk_payment_fare
        FOREIGN KEY (fare_id)
        REFERENCES fare(fare_id),

    CONSTRAINT ck_payment_amount
        CHECK (amount >= 0),

    CONSTRAINT ck_payment_method
        CHECK (
            payment_method IN (
                'CASH',
                'ELECTRONIC'
            )
        ),

    CONSTRAINT ck_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT ck_payment_paid_at
        CHECK (
            (
                payment_status = 'COMPLETED'
                AND paid_at IS NOT NULL
            )
            OR
            (
                payment_status <> 'COMPLETED'
            )
        )
);


CREATE TABLE payment_transaction (
    transaction_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          INTEGER NOT NULL,

    provider_reference  VARCHAR(100),

    transaction_status  VARCHAR(20) NOT NULL,

    amount              DECIMAL(10,2) NOT NULL,
    currency            VARCHAR(3) NOT NULL,

    failure_reason      VARCHAR(255),

    processed_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_transaction_payment
        FOREIGN KEY (payment_id)
        REFERENCES payment(payment_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_payment_transaction_status
        CHECK (
            transaction_status IN (
                'PENDING',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT ck_payment_transaction_amount
        CHECK (amount >= 0)
);


CREATE INDEX idx_payment_trip
    ON payment(trip_id);


CREATE INDEX idx_payment_customer_status
    ON payment(
        customer_id,
        payment_status
    );


CREATE INDEX idx_payment_transaction_payment_processed
    ON payment_transaction(
        payment_id,
        processed_at
    );



-- =========================================================
-- Notification
-- notification-service -> notification_db
--
-- recipient_user_id is a logical reference to auth_db.
-- =========================================================

\connect notification_db


CREATE TABLE notification (
    notification_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_event_id      VARCHAR(100) NOT NULL,
    dedup_key            VARCHAR(100) NOT NULL UNIQUE,

    recipient_user_id    INTEGER NOT NULL,

    notification_type    VARCHAR(50) NOT NULL,
    notification_status  VARCHAR(20) NOT NULL,

    message              VARCHAR(255) NOT NULL,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_notification_status
        CHECK (
            notification_status IN (
                'PENDING',
                'PROCESSED',
                'FAILED'
            )
        )
);


CREATE TABLE notification_delivery (
    delivery_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id      INTEGER NOT NULL,

    channel              VARCHAR(20) NOT NULL,
    provider             VARCHAR(50) NOT NULL,

    delivery_status      VARCHAR(20) NOT NULL,
    attempt_count        INTEGER NOT NULL DEFAULT 0,

    provider_message_id  VARCHAR(100),
    failure_reason       VARCHAR(255),

    sent_at              TIMESTAMPTZ,
    delivered_at         TIMESTAMPTZ,

    CONSTRAINT fk_notification_delivery_notification
        FOREIGN KEY (notification_id)
        REFERENCES notification(notification_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_notification_delivery_status
        CHECK (
            delivery_status IN (
                'PENDING',
                'SENT',
                'DELIVERED',
                'FAILED'
            )
        ),

    CONSTRAINT ck_notification_delivery_attempt_count
        CHECK (
            attempt_count >= 0
        )
);


CREATE INDEX idx_notification_recipient_created
    ON notification(
        recipient_user_id,
        created_at DESC
    );


CREATE INDEX idx_notification_source_event
    ON notification(source_event_id);


CREATE INDEX idx_notification_delivery_status
    ON notification_delivery(delivery_status);



-- =========================================================
-- Rating & Review
-- review-service -> review_db
--
-- trip/customer/driver IDs are logical references.
-- =========================================================

\connect review_db


CREATE TABLE review (
    review_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    trip_id      INTEGER NOT NULL UNIQUE,
    customer_id  INTEGER NOT NULL,
    driver_id    INTEGER NOT NULL,

    score        INTEGER NOT NULL,
    comment      VARCHAR(255),

    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_review_score
        CHECK (
            score BETWEEN 1 AND 5
        )
);


CREATE TABLE driver_rating (
    driver_id      INTEGER PRIMARY KEY,

    average_score  DECIMAL(3,2) NOT NULL DEFAULT 0,
    review_count   INTEGER NOT NULL DEFAULT 0,

    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_driver_rating_average
        CHECK (
            average_score BETWEEN 0 AND 5
        ),

    CONSTRAINT ck_driver_rating_count
        CHECK (
            review_count >= 0
        )
);


CREATE INDEX idx_review_driver_created
    ON review(
        driver_id,
        created_at DESC
    );


CREATE INDEX idx_review_customer_created
    ON review(
        customer_id,
        created_at DESC
    );



-- =========================================================
-- Reporting
-- report-service -> reporting_db
--
-- Reporting contains read-model projections only.
-- No physical FK to source contexts.
-- =========================================================

\connect reporting_db


CREATE TABLE trip_report (
    report_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    period_start      DATE NOT NULL,
    period_end        DATE NOT NULL,

    trip_count        INTEGER NOT NULL,
    completed_count   INTEGER NOT NULL,
    canceled_count    INTEGER NOT NULL,

    completion_rate   DECIMAL(5,2) NOT NULL,
    cancelation_rate  DECIMAL(5,2) NOT NULL,

    generated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_trip_report_period
        CHECK (
            period_end >= period_start
        ),

    CONSTRAINT ck_trip_report_counts
        CHECK (
            trip_count >= 0
            AND completed_count >= 0
            AND canceled_count >= 0
        ),

    CONSTRAINT ck_trip_report_rates
        CHECK (
            completion_rate BETWEEN 0 AND 1
            AND cancelation_rate BETWEEN 0 AND 1
        )
);


CREATE TABLE revenue_report (
    report_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    period_start               DATE NOT NULL,
    period_end                 DATE NOT NULL,

    total_revenue              DECIMAL(10,2) NOT NULL,
    currency                   VARCHAR(3) NOT NULL,

    successful_payment_count   INTEGER NOT NULL,
    failed_payment_count       INTEGER NOT NULL,

    generated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_revenue_report_period
        CHECK (
            period_end >= period_start
        ),

    CONSTRAINT ck_revenue_report_values
        CHECK (
            total_revenue >= 0
            AND successful_payment_count >= 0
            AND failed_payment_count >= 0
        )
);


CREATE TABLE driver_performance (
    performance_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    driver_id         INTEGER NOT NULL,

    period_start      DATE NOT NULL,
    period_end        DATE NOT NULL,

    trip_count        INTEGER NOT NULL,
    completed_count   INTEGER NOT NULL,
    canceled_count    INTEGER NOT NULL,

    completion_rate   DECIMAL(5,2) NOT NULL,
    cancelation_rate  DECIMAL(5,2) NOT NULL,

    rating            DECIMAL(3,2) NOT NULL,

    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_driver_performance_period
        CHECK (
            period_end >= period_start
        ),

    CONSTRAINT ck_driver_performance_counts
        CHECK (
            trip_count >= 0
            AND completed_count >= 0
            AND canceled_count >= 0
        ),

    CONSTRAINT ck_driver_performance_rates
        CHECK (
            completion_rate BETWEEN 0 AND 1
            AND cancelation_rate BETWEEN 0 AND 1
        ),

    CONSTRAINT ck_driver_performance_rating
        CHECK (
            rating BETWEEN 0 AND 5
        ),

    CONSTRAINT uq_driver_performance_period
        UNIQUE (
            driver_id,
            period_start,
            period_end
        )
);


CREATE INDEX idx_trip_report_period
    ON trip_report(
        period_start,
        period_end
    );


CREATE INDEX idx_revenue_report_period
    ON revenue_report(
        period_start,
        period_end
    );


CREATE INDEX idx_driver_performance_driver_period
    ON driver_performance(
        driver_id,
        period_start,
        period_end
    );



-- =========================================================
-- Audit
-- audit-service -> audit_db
--
-- actor_user_id is a logical reference to auth_db.
-- =========================================================

\connect audit_db


CREATE TABLE audit_log (
    audit_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id        VARCHAR(100),
    correlation_id  VARCHAR(100),

    actor_user_id   INTEGER,

    action          VARCHAR(50) NOT NULL,
    entity_type     VARCHAR(50) NOT NULL,
    entity_id       VARCHAR(100) NOT NULL,

    success         BOOLEAN NOT NULL,

    ip_address      VARCHAR(45),

    metadata        JSON,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_audit_actor_created
    ON audit_log(
        actor_user_id,
        created_at DESC
    );


CREATE INDEX idx_audit_entity
    ON audit_log(
        entity_type,
        entity_id
    );


CREATE INDEX idx_audit_correlation
    ON audit_log(correlation_id);


CREATE INDEX idx_audit_event
    ON audit_log(event_id);