syntax = "proto3";

package cab.notification.v1;

import "common/common.proto";

service NotificationService {
  rpc ListNotifications(ListNotificationsRequest) returns (NotificationList);
}

message Notification {
  string notification_id = 1;
  string source_event_id = 2;
  string recipient_user_id = 3;
  string type = 4;
  string reference = 5;
  string message = 6;
  string status = 7; // SENT
  string created_at = 8;
}

message ListNotificationsRequest {
  cab.common.v1.RequestContext context = 1;
  int32 limit = 2;
}

message NotificationList {
  repeated Notification items = 1;
}
