syntax = "proto3";

package cab.payment.v1;

import "common/common.proto";

service PaymentService {
  rpc GetPayment(GetPaymentRequest) returns (Payment);
  rpc GetPaymentByBooking(GetPaymentByBookingRequest) returns (Payment);
  rpc PayExistingPayment(PayExistingPaymentRequest) returns (Payment);
  rpc PaymentCallback(PaymentCallbackRequest) returns (Payment);
}

message Payment {
  string payment_id = 1;
  string booking_id = 2;
  optional string trip_id = 3;
  string customer_id = 4;
  double amount = 5;
  bool eligible = 6;
  string status = 7; // PENDING | COMPLETED
  optional string idempotency_key = 8;
  string created_at = 9;
  optional string paid_at = 10;
}

message GetPaymentRequest {
  cab.common.v1.RequestContext context = 1;
  string payment_id = 2;
}

message GetPaymentByBookingRequest {
  cab.common.v1.RequestContext context = 1;
  string booking_id = 2;
}

message PayExistingPaymentRequest {
  cab.common.v1.RequestContext context = 1;
  string payment_id = 2;
  string idempotency_key = 3;
}

message PaymentCallbackRequest {
  cab.common.v1.RequestContext context = 1;
  string payment_id = 2;
  string status = 3; // COMPLETED in demo
}
