syntax = "proto3";

package cab.report.v1;

import "common/common.proto";

service ReportService {
  rpc GetTripReport(
    GetTripReportRequest
  ) returns (TripReport);

  rpc GetRevenueReport(
    GetRevenueReportRequest
  ) returns (RevenueReport);

  rpc GetDriverPerformanceReport(
    GetDriverPerformanceReportRequest
  ) returns (DriverPerformanceList);
}

message GetTripReportRequest {
  cab.common.v1.RequestContext context = 1;
  string from = 2;
  string to = 3;
}

message TripReport {
  string from = 1;
  string to = 2;

  int64 total_trips = 3;
  int64 completed_trips = 4;
  int64 canceled_trips = 5;

  double completion_rate = 6;
  double cancellation_rate = 7;

  optional string generated_at = 8;
}

message GetRevenueReportRequest {
  cab.common.v1.RequestContext context = 1;
  string from = 2;
  string to = 3;
}

message RevenueReport {
  string from = 1;
  string to = 2;

  double total_revenue = 3;

  int64 successful_payments = 4;
  int64 failed_payments = 5;

  optional string generated_at = 6;
  optional string currency = 7;
}

message GetDriverPerformanceReportRequest {
  cab.common.v1.RequestContext context = 1;

  string from = 2;
  string to = 3;

  optional string driver_id = 4;
}

message DriverPerformance {
  string driver_id = 1;

  string from = 2;
  string to = 3;

  int64 total_trips = 4;
  int64 completed_trips = 5;
  int64 canceled_trips = 6;

  double completion_rate = 7;
  double average_rating = 8;

  optional string generated_at = 9;
  optional double cancellation_rate = 10;
}

message DriverPerformanceList {
  repeated DriverPerformance items = 1;
}